### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by eko234** [raiguard/harpoon.kak#1]
.Hi, I was doing something similar with lua too, just wanted to pass by and suggest some ideas that I think match with your roadmap,
I made this plugin that is not portable at all and basically I alone use:
https://github.com/eko234/meats/blob/master/meats.kak

I'm using flatdb to store data from files and I load it dinamically from the plugin.

I think nice features are sorting by last use, and being able to bind them to any key, like it was a layer on top of registers.

I say this not because one solution is better than the other, but maybe I can collaborate with your plugin which seems more organized than mine, please let me know what you think, and sorry for using issues for this. :V

have a nice day :)

**Comment by raiguard** [comment]
Hey! No problem at all using issues for this.

Your solution is interesting, but seems a tad overcomplicated. I simply store the positions in a native kakoune option. In the future I will add the capability to persist the harpoons per project, but that will be as simple as saving a file in `.local` that contains the contents of the option, and loading that in when kak is opened.

I think binding them to any key is overkill. If you have more than three or four harpoons, it's a sign that you're doing too many things at once and need to narrow your focus. The built-in keybindings have shortcuts for nine, but you could add as many as you want and / or define your own shortcuts.

Thanks for checking out the plugin!

**Comment by eko234** [comment]
Well thath's a good point, yes indeed I usually overcomplicate things a little :V, I will keep an eye on this plugin, thanks.
