### ISSUE TITLE
Persistence + per branch tracking?

### ISSUE THREAD

**Issue by joncol** [raiguard/harpoon.kak#2]
Hi, just to be clear, the harpoons are not saved to file currently, right? So that you can access your harpoons after quitting and reopening `kak`?

If so, do you have any plans to implement this? Would also be nice with the feature from the Neovim version of Harpoon that keeps track of harpoons per branch.

Anyway, thanks for the plugin!

**Comment by raiguard** [comment]
Sorry for missing this, my github notifications are a mess right now.

I plan on persisting harpoons by the $PWD of the kakoune server in the future. As for branches, I didn't think about that, but it sounds awesome so I could potentially do that as well.

**Comment by raiguard** [comment]
This ended up being _significantly_ easier than I had anticipated. I've been wanting this for a while, and now it's finally in! Let me know if you have any problems with it.
